name: sermacs-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - plotly
  - matplotlib
  - numpy
  - scipy
  - jupyterlab
  - rdkit
  - sklearn
  - pip
  - pip:
    - nmrglue
